services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
      - BACKEND_SWAGGER_URL=${BACKEND_SWAGGER_URL}
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - ./backend/src:/backend/src
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - "${FRONTEND_PORT}:5173"
    depends_on:
      - backend
