services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${API_PORT}
    volumes:
      - ./src:/app/src
    ports:
      - '${API_PORT}:3000'
    depends_on:
      - db
