services:

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: ["start-dev","--import-realm", "--hostname-strict=false"]                     
    environment:
      - KC_HOSTNAME=localhost
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_IMPORT=/opt/keycloak/data/import/keycloak-realm.json
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json      
    ports:
      - "8080:8080"
    healthcheck:
      test: cat /proc/net/tcp | grep '00000000:1F90 00000000:0000' || exit 1
      interval: 15s
      timeout: 2s
      retries: 15  
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
      - BACKEND_SWAGGER_URL=${BACKEND_SWAGGER_URL}
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - ./backend/src:/backend/src
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - db
      - keycloak

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - "${FRONTEND_PORT}:5173"
    depends_on:
      - backend
